DROP DATABASE GabeSuperMarket;

CREATE DATABASE GabeSuperMarket;

USE GabeSuperMarket;

CREATE TABLE PRODUCT(
	PRODUCTID						BIGINT UNIQUE PRIMARY KEY NOT NULL AUTO_INCREMENT,
	PRODUCTNAME						VARCHAR(100),
	BARCODE							VARCHAR(13),
	MEASUREMENTUNITS                BIGINT,
	MEASUREMENTVALUE				NUMERIC(5,2),
	DESCRIPTION						VARCHAR(100),
	IMAGE							TEXT
 );
  
	
CREATE USER 'gabe'@'localhost' IDENTIFIED BY 'gabe';
GRANT ALL ON GabeSuperMarket.* TO 'gabe'@'localhost';
FLUSH PRIVILEGES;